### ISSUE TITLE
As a user, I would like to use snippets which make writing playbooks easier

### ISSUE THREAD

**Issue by Jakeeyturner** [IBM-Blockchain/blockchain-vscode-extension#2041]
## Description

As a user, it would be nice to be able to be able to generate and use autocomplete snippets for organisations, peers, channels, contracts, gateways, etc.

To add a new organisation to my playbook which has a two peers and a CA I need to write the following:

```
- &Org1
msp:
  id: "Org1MSP"
  admin:
    identity: "org1Admin"
    secret: "org1Adminpw"
  ibp:
    display_name: "Org1 MSP"
ca: &Org1CA
  id: "Org1CA"
  admin_identity: "admin"
  admin_secret: "adminpw"
  tls:
    enabled: true
  docker:
    name: ca.org1.example.com
    hostname: ca.org1.example.com
    port: 18050
  ibp:
    display_name: "Org1 CA"
peers:
  - &Org1Peer1
    id: "Org1Peer1"
    identity: "org1peer1"
    secret: "org1peer1pw"
    database_type: couchdb
    tls:
      enabled: true
      identity: "org1peer1tls"
      secret: "org1peer1tlspw"
    docker:
      name: peer0.org1.example.com
      hostname: peer0.org1.example.com
      port: 18051
      chaincode_port: 18052
      operations_port: 18053
      couchdb:
        name: couchdb0.org1.example.com
        hostname: couchdb0.org1.example.com
        port: 18054
    ibp:
      display_name: "Org1 Peer1"
  - &Org1Peer2
    id: "Org1Peer2"
    identity: "org1peer2"
    secret: "org1peer2pw"
    database_type: couchdb
    tls:
      enabled: true
      identity: "org1peer2tls"
      secret: "org1peer2tlspw"
    docker:
      name: peer1.org1.example.com
      hostname: peer1.org1.example.com
      port: 18055
      chaincode_port: 18056
      operations_port: 18057
      couchdb:
        name: couchdb1.org1.example.com
        hostname: couchdb1.org1.example.com
        port: 18058
    ibp:
      display_name: "Org1 Peer2"
nodes: "{{ playbook_dir }}/nodes/Org1"
wallet: "{{ playbook_dir }}/wallets/Org1"
gateways: "{{ playbook_dir }}/gateways/Org1"
```

This is _quite_ a lot to write without any kind of language support or suggestions of how to use the role.

Having auto-completable snippets for a developer to write/edit playbooks would make it a lot easier - that way they can just edit/change values and add additional blocks where necessary.
## Steps to Reproduce

1.
2.
3.

## Existing issues

- [ ] [Stack Overflow issues](https://stackoverflow.com/questions/tagged/ibp-vscode-extension)
- [ ] [GitHub Issues](https://github.com/IBM-Blockchain/blockchain-vscode-extension/issues)

## Your Environment

* IBM Blockchain Platform Extension Version:
* Visual Studio Code version:
* Environment name and version (e.g. Node.js v8.12.0, npm v6.4.1):
* Operating System and version:
* Link to your project:
